/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.andicar.activity;

public final class R {
    public static final class array {
        /**  Used in gps track (minimum distance betwee 2 recording points) 
    <string-array name="gpstrack_preference_mindistance_entries">
        <item>0</item>
        <item>1 m / 1.09 yd</item>
        <item>3 m / 3.28 yd</item>
        <item>5 m / 5.47 yd</item>
        <item>10 m / 10.94 yd</item>
        <item>50 m / 54.68 yd</item>
        <item>100 m / 109.36 yd</item>
    </string-array>
     values in meter 
    <string-array name="gpstrack_preference_mindistance_values">
        <item>0</item>
        <item>1</item>
        <item>3</item>
        <item>5</item>
        <item>10</item>
        <item>50</item>
        <item>100</item>
    </string-array>

 Used in gps track (maximum value of accuracy) 
         */
        public static final int gpstrack_preference_maxaccuracy_entries=0x7f040003;
        /**  values in meter 
         */
        public static final int gpstrack_preference_maxaccuracy_values=0x7f040004;
        /**  Used in gps track. Maximum value of percentage of skipped track points.
    Tracking will be automatically stopped over this limit 
         */
        public static final int gpstrack_preference_maxaccuracyshutdownlimit_entries=0x7f040005;
        /**  values in meter 
         */
        public static final int gpstrack_preference_maxaccuracyshutdownlimit_values=0x7f040006;
        /**  Used in gps track (minimum time betwee 2 recording points) 
         */
        public static final int gpstrack_preference_mintime_entries=0x7f040001;
        /**  values in miliseconds 
         */
        public static final int gpstrack_preference_mintime_values=0x7f040002;
        /**  report file formats  
         */
        public static final int report_formats=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int header_bg=0x7f050002;
        public static final int label_bg=0x7f050001;
        public static final int mandatory_bg=0x7f050000;
        public static final int search_dialog_spinner_bg=0x7f050004;
        public static final int separator_bg=0x7f050003;
    }
    public static final class drawable {
        public static final int andicar_gps0=0x7f020000;
        public static final int andicar_gps1=0x7f020001;
        public static final int andicar_gps2=0x7f020002;
        public static final int andicar_gps_anim=0x7f020003;
        public static final int btn_donate=0x7f020004;
        public static final int car2=0x7f020005;
        public static final int ic_menu_add=0x7f020006;
        public static final int ic_menu_expenses=0x7f020007;
        public static final int ic_menu_gpstrack=0x7f020008;
        public static final int ic_menu_help=0x7f020009;
        public static final int ic_menu_info_details=0x7f02000a;
        public static final int ic_menu_mileage=0x7f02000b;
        public static final int ic_menu_preferences=0x7f02000c;
        public static final int ic_menu_refuel=0x7f02000d;
        public static final int ic_menu_report=0x7f02000e;
        public static final int ic_menu_search=0x7f02000f;
        public static final int ic_menu_send=0x7f020010;
        public static final int ic_menu_show_active=0x7f020011;
        public static final int ic_menu_show_inactive=0x7f020012;
        public static final int ic_statusbar_reportservice_start=0x7f020013;
        public static final int stat_sys_error=0x7f020014;
        public static final int stat_sys_warning=0x7f020015;
    }
    public static final class id {
        public static final int aboutDonateEUR=0x7f070003;
        public static final int aboutDonateUSD=0x7f070004;
        public static final int acUserComment=0x7f070048;
        public static final int btnBackup=0x7f070006;
        public static final int btnDelete=0x7f070008;
        public static final int btnExpenseInsert=0x7f070071;
        public static final int btnExpenseList=0x7f070070;
        public static final int btnGPSTrackInsert=0x7f070062;
        public static final int btnGPSTrackList=0x7f070061;
        public static final int btnMileageInsert=0x7f07005a;
        public static final int btnMileageList=0x7f070059;
        public static final int btnPickDate=0x7f070046;
        public static final int btnPickTime=0x7f070047;
        public static final int btnRefuelInsert=0x7f07006a;
        public static final int btnRefuelList=0x7f070069;
        public static final int btnRestore=0x7f070007;
        public static final int btnStartStopGpsTrack=0x7f07004e;
        public static final int ckIsActive=0x7f070013;
        public static final int ckIsCreateMileage=0x7f07004d;
        public static final int ckIsExcludeFromMileageCost=0x7f070049;
        public static final int ckIsFullRefuel=0x7f070088;
        public static final int ckIsSendEmail=0x7f07008f;
        public static final int ckIsUseGPX=0x7f070051;
        public static final int ckIsUseKML=0x7f070050;
        public static final int etAmount=0x7f07003b;
        public static final int etCarModel=0x7f070015;
        public static final int etCarRegNo=0x7f07000d;
        public static final int etCode=0x7f070019;
        public static final int etConversionRate=0x7f07003e;
        public static final int etCurrencyRate=0x7f07001f;
        public static final int etDateFromSearch=0x7f07002a;
        public static final int etDateToSearch=0x7f07002c;
        public static final int etDocumentNo=0x7f070044;
        public static final int etIndex=0x7f070042;
        public static final int etIndexStart=0x7f07000f;
        public static final int etLicenseNo=0x7f070032;
        public static final int etName=0x7f07000b;
        public static final int etPrice=0x7f07008d;
        public static final int etQuantity=0x7f070087;
        public static final int etUserComment=0x7f070017;
        public static final int etUserCommentSearch=0x7f070026;
        public static final int etUserInput=0x7f07007d;
        public static final int genRootViewGvgRootroup=0x7f070025;
        public static final int gpstrackmap=0x7f07004c;
        public static final int info=0x7f070052;
        public static final int llAbout=0x7f070001;
        public static final int llBaseUOMQtyZone=0x7f070089;
        public static final int llConversionRateZone=0x7f07003c;
        public static final int llExpenseZone=0x7f07006b;
        public static final int llGPSTrackZone=0x7f07005b;
        public static final int llMileageZone=0x7f070053;
        public static final int llRefuelZone=0x7f070063;
        public static final int llStatistcsZone=0x7f070072;
        public static final int lvBackupList=0x7f070009;
        public static final int lvZones=0x7f070079;
        public static final int rbInsertModeIndex=0x7f070081;
        public static final int rbInsertModeMileage=0x7f070083;
        public static final int rgMileageInsertMode=0x7f070082;
        public static final int setDateFromSearch=0x7f070085;
        public static final int spnCar=0x7f070034;
        public static final int spnCarSearch=0x7f070030;
        public static final int spnCurrency=0x7f070012;
        public static final int spnCurrencyFrom=0x7f07001b;
        public static final int spnCurrencyTo=0x7f07001d;
        public static final int spnDriver=0x7f070035;
        public static final int spnDriverSearch=0x7f07002e;
        public static final int spnExpCategory=0x7f070037;
        public static final int spnExpCategorySearch=0x7f07004b;
        public static final int spnExpType=0x7f070039;
        public static final int spnExpTypeSearch=0x7f070028;
        public static final int spnReportOptionsFormat=0x7f070091;
        public static final int spnUomFrom=0x7f07009e;
        public static final int spnUomLength=0x7f070010;
        public static final int spnUomTo=0x7f07009f;
        public static final int spnUomVolume=0x7f070011;
        public static final int tvAbout1=0x7f070002;
        public static final int tvAbout2=0x7f070005;
        public static final int tvAmountLabel=0x7f07003a;
        public static final int tvAmountValue=0x7f07008e;
        public static final int tvBaseUOMQtyLabel=0x7f07008a;
        public static final int tvBaseUOMQtyValue=0x7f07008b;
        public static final int tvCalculatedTextContent=0x7f07007f;
        public static final int tvCalculatedTextLabel=0x7f07007e;
        public static final int tvCarDriverLabel=0x7f07007a;
        public static final int tvCarLabel=0x7f07002f;
        public static final int tvCarRegNoLabel=0x7f07000c;
        public static final int tvCodeLabel=0x7f070018;
        public static final int tvConversionRateLabel=0x7f07003d;
        public static final int tvConvertedAmountLabel=0x7f07003f;
        public static final int tvConvertedAmountValue=0x7f070040;
        public static final int tvCurrencyFrom=0x7f07001a;
        public static final int tvCurrencyRateLabel=0x7f07001e;
        public static final int tvCurrencyRateToLabel=0x7f070020;
        public static final int tvCurrencyTo=0x7f07001c;
        public static final int tvDateFromLabel=0x7f070029;
        public static final int tvDateTimeHdrLabel=0x7f070084;
        public static final int tvDateTimeValue=0x7f070045;
        public static final int tvDateToLabel=0x7f07002b;
        public static final int tvDocumentNoLabel=0x7f070043;
        public static final int tvDriverLabel=0x7f07002d;
        public static final int tvExpCategoryLabel=0x7f07004a;
        public static final int tvExpTypeLabel=0x7f070027;
        public static final int tvExpenseCategoryLabel=0x7f070036;
        public static final int tvExpenseHdr=0x7f07006c;
        public static final int tvExpenseTypeLabel=0x7f070038;
        public static final int tvFileFormatLabel=0x7f07004f;
        public static final int tvFormatLabel=0x7f070090;
        public static final int tvGPSTrackHdr=0x7f07005c;
        public static final int tvIndexLabel=0x7f070041;
        public static final int tvIndexStartLabel=0x7f07000e;
        public static final int tvInsertModeHdrLabel=0x7f070080;
        public static final int tvInverseRateLabel=0x7f070021;
        public static final int tvInverseRateToLabel=0x7f070023;
        public static final int tvInverseRateValue=0x7f070022;
        public static final int tvLicenseNoLabel=0x7f070031;
        public static final int tvMileageHdr=0x7f070054;
        public static final int tvModelLabel=0x7f070014;
        public static final int tvNameLabel=0x7f07000a;
        public static final int tvPriceLabel=0x7f07008c;
        public static final int tvQuantityLabel=0x7f070086;
        public static final int tvRefuelHdr=0x7f070064;
        public static final int tvShortAboutLbl=0x7f070078;
        public static final int tvStartStopIndexHdr=0x7f07007b;
        public static final int tvStatisticsHdr=0x7f070073;
        public static final int tvThreeLineListCarReportHdr=0x7f070074;
        public static final int tvThreeLineListExpenseText1=0x7f07006d;
        public static final int tvThreeLineListExpenseText2=0x7f07006e;
        public static final int tvThreeLineListExpenseText3=0x7f07006f;
        public static final int tvThreeLineListGPSTrackHdr=0x7f07005d;
        public static final int tvThreeLineListGPSTrackText1=0x7f07005e;
        public static final int tvThreeLineListGPSTrackText2=0x7f07005f;
        public static final int tvThreeLineListGPSTrackText3=0x7f070060;
        public static final int tvThreeLineListMileageHdr=0x7f070055;
        public static final int tvThreeLineListMileageText1=0x7f070056;
        public static final int tvThreeLineListMileageText2=0x7f070057;
        public static final int tvThreeLineListMileageText3=0x7f070058;
        public static final int tvThreeLineListRefuelHdr=0x7f070065;
        public static final int tvThreeLineListRefuelText1=0x7f070066;
        public static final int tvThreeLineListRefuelText2=0x7f070067;
        public static final int tvThreeLineListRefuelText3=0x7f070068;
        public static final int tvThreeLineListReportText1=0x7f070095;
        public static final int tvThreeLineListReportText2=0x7f070096;
        public static final int tvThreeLineListReportText3=0x7f070097;
        public static final int tvThreeLineListStatisticsText1=0x7f070075;
        public static final int tvThreeLineListStatisticsText2=0x7f070076;
        public static final int tvThreeLineListStatisticsText3=0x7f070077;
        public static final int tvThreeLineListText1=0x7f070092;
        public static final int tvThreeLineListText2=0x7f070093;
        public static final int tvThreeLineListText3=0x7f070094;
        public static final int tvTwoLineListReportText1=0x7f07009a;
        public static final int tvTwoLineListReportText2=0x7f07009b;
        public static final int tvTwoLineListText1=0x7f070098;
        public static final int tvTwoLineListText2=0x7f070099;
        public static final int tvTwoLineSingleChoiceListText1=0x7f07009c;
        public static final int tvTwoLineSingleChoiceListText2=0x7f07009d;
        public static final int tvUserComment=0x7f070024;
        public static final int tvUserCommentLabel=0x7f070016;
        public static final int tvUserInputLabel=0x7f07007c;
        public static final int tvWarningLabel=0x7f070033;
        public static final int vgRoot=0x7f070000;
    }
    public static final class layout {
        public static final int about_activity=0x7f030000;
        public static final int backup_restore_activity=0x7f030001;
        public static final int car_edit_activity=0x7f030002;
        public static final int currency_edit_activity=0x7f030003;
        public static final int currencyrate_edit_activity=0x7f030004;
        public static final int daily_mileage_search_dialog=0x7f030005;
        public static final int driver_edit_activity=0x7f030006;
        public static final int expense_edit_activity=0x7f030007;
        public static final int expensecategory_edit_activity=0x7f030008;
        public static final int expenses_search_dialog=0x7f030009;
        public static final int expensetype_edit_activity=0x7f03000a;
        public static final int gps_track_map=0x7f03000b;
        public static final int gpstrackcontroller_activity=0x7f03000c;
        public static final int main_activity=0x7f03000d;
        public static final int main_screen_preference_activity=0x7f03000e;
        public static final int mileage_edit_activity=0x7f03000f;
        public static final int mileage_search_dialog=0x7f030010;
        public static final int refuel_edit_activity=0x7f030011;
        public static final int refuel_search_dialog=0x7f030012;
        public static final int report_options_dialog=0x7f030013;
        public static final int threeline_list_activity=0x7f030014;
        public static final int threeline_listreport_activity=0x7f030015;
        public static final int twoline_list_activity=0x7f030016;
        public static final int twoline_listreport_activity=0x7f030017;
        public static final int twoline_singlechoice=0x7f030018;
        public static final int uom_edit_activity=0x7f030019;
        public static final int uomconversion_edit_activity=0x7f03001a;
    }
    public static final class string {
        public static final int APP_ACTIVITY_ABOUT=0x7f060039;
        public static final int APP_ACTIVITY_BKRESTORE=0x7f06003a;
        public static final int APP_ACTIVITY_CAREDIT=0x7f060027;
        public static final int APP_ACTIVITY_CARLIST=0x7f060028;
        public static final int APP_ACTIVITY_CURRENCYEDIT=0x7f060034;
        public static final int APP_ACTIVITY_CURRENCYLIST=0x7f060033;
        public static final int APP_ACTIVITY_CURRENCYRATEEDIT=0x7f06003f;
        public static final int APP_ACTIVITY_CURRENCYRATELIST=0x7f06003e;
        public static final int APP_ACTIVITY_DRIVEREDIT=0x7f060025;
        public static final int APP_ACTIVITY_DRIVERLIST=0x7f060026;
        public static final int APP_ACTIVITY_EXPCATEGORYEDIT=0x7f06002c;
        public static final int APP_ACTIVITY_EXPCATEGORYLIST=0x7f06002b;
        public static final int APP_ACTIVITY_EXPENSEEDIT=0x7f06003c;
        public static final int APP_ACTIVITY_EXPENSELIST=0x7f06003b;
        public static final int APP_ACTIVITY_EXPTYPEEDIT=0x7f06002e;
        public static final int APP_ACTIVITY_EXPTYPELIST=0x7f06002d;
        public static final int APP_ACTIVITY_GPSPREFERENCES=0x7f06002a;
        public static final int APP_ACTIVITY_GPSTRACKCONTROLLER=0x7f060040;
        public static final int APP_ACTIVITY_MAINSCREENPREF=0x7f06003d;
        public static final int APP_ACTIVITY_MILEAGEEDIT=0x7f060036;
        public static final int APP_ACTIVITY_MILEAGE_LIST=0x7f060035;
        public static final int APP_ACTIVITY_PREFERENCES=0x7f060029;
        public static final int APP_ACTIVITY_REFUEL=0x7f060038;
        public static final int APP_ACTIVITY_REFUEL_LIST=0x7f060037;
        public static final int APP_ACTIVITY_UOMCONVERSIONEDIT=0x7f060032;
        public static final int APP_ACTIVITY_UOMCONVERSIONLIST=0x7f060031;
        public static final int APP_ACTIVITY_UOMEDIT=0x7f060030;
        public static final int APP_ACTIVITY_UOMLIST=0x7f06002f;
        public static final int APP_DESCRIPTION=0x7f060024;
        public static final int APP_NAME=0x7f060023;
        public static final int BKRESTORE_ACTIVITY_BACKUPBTN_CAPTION=0x7f0600ef;
        public static final int BKRESTORE_ACTIVITY_BKFAILED_MESSAGE=0x7f0600f4;
        public static final int BKRESTORE_ACTIVITY_BKOK_MESSAGE=0x7f0600f3;
        public static final int BKRESTORE_ACTIVITY_DELETEBK_CAPTION=0x7f0600f1;
        public static final int BKRESTORE_ACTIVITY_DELETE_CONFIRM=0x7f0600f5;
        public static final int BKRESTORE_ACTIVITY_EXISTINGBKS_LABEL=0x7f0600f2;
        public static final int BKRESTORE_ACTIVITY_RESTOREBTN_CAPTION=0x7f0600f0;
        public static final int BKRESTORE_ACTIVITY_RESTOREOK_MESSAGE=0x7f0600f7;
        public static final int BKRESTORE_ACTIVITY_RESTORE_CONFIRM=0x7f0600f6;
        public static final int CAR_EDIT_ACTIVITY_CURRENCY=0x7f060099;
        public static final int CAR_EDIT_ACTIVITY_MODEL=0x7f060094;
        public static final int CAR_EDIT_ACTIVITY_REG_NO=0x7f060095;
        public static final int CAR_EDIT_ACTIVITY_STARTINDEX=0x7f060098;
        public static final int CAR_EDIT_ACTIVITY_UOMLENGTH=0x7f060096;
        public static final int CAR_EDIT_ACTIVITY_UOMVOLUME=0x7f060097;
        public static final int CURRENCYRATE_EDIT_ACTIVITY_CURRENCYFROM_LABEL=0x7f0600fa;
        public static final int CURRENCYRATE_EDIT_ACTIVITY_CURRENCYRATETO_LABEL=0x7f0600fd;
        public static final int CURRENCYRATE_EDIT_ACTIVITY_CURRENCYRATE_LABEL=0x7f0600fc;
        public static final int CURRENCYRATE_EDIT_ACTIVITY_CURRENCYTO_LABEL=0x7f0600fb;
        public static final int CURRENCYRATE_EDIT_ACTIVITY_INVERSECURRENCYRATE_LABEL=0x7f0600fe;
        public static final int CURRENCYRATE_EDIT_ACTIVITY_MAXALLOWEDDECIMALS_LABEL=0x7f0600ff;
        public static final int CURRENCYRATE_EDIT_ACTIVITY_TVCURRENCYRATE_TAG=0x7f060100;
        public static final int CURRENCY_EDIT_ACTIVITY_CODE=0x7f0600a5;
        public static final int CURRENT_CAR_DELETE_ERROR_MESSAGE=0x7f06009b;
        public static final int CURRENT_CAR_INACTIVATE_ERROR_MESSAGE=0x7f06009c;
        public static final int CURRENT_DRIVER_DELETE_ERROR_MESSAGE=0x7f060092;
        public static final int CURRENT_DRIVER_INACTIVATE_ERROR_MESSAGE=0x7f060093;
        public static final int CURR_UOMS=0x7f0600b2;
        public static final int DRIVER_EDIT_ACTIVITY_LICENSE_NO=0x7f06008f;
        public static final int ERR_000=0x7f060000;
        public static final int ERR_001=0x7f060001;
        public static final int ERR_002=0x7f060002;
        public static final int ERR_003=0x7f060003;
        public static final int ERR_004=0x7f060004;
        public static final int ERR_005=0x7f060005;
        public static final int ERR_006=0x7f060006;
        /** <string name="ERR_007">"Error on modifying record!"</string>
         */
        public static final int ERR_008=0x7f060007;
        public static final int ERR_009=0x7f060008;
        public static final int ERR_010=0x7f060009;
        public static final int ERR_011=0x7f06000a;
        public static final int ERR_012=0x7f06000b;
        public static final int ERR_013=0x7f06000c;
        public static final int ERR_014=0x7f06000d;
        public static final int ERR_015=0x7f06000e;
        public static final int ERR_016=0x7f06000f;
        public static final int ERR_017=0x7f060010;
        public static final int ERR_018=0x7f060011;
        public static final int ERR_019=0x7f060012;
        public static final int ERR_020=0x7f060013;
        public static final int ERR_021=0x7f060014;
        public static final int ERR_022=0x7f060015;
        public static final int ERR_023=0x7f060016;
        public static final int ERR_024=0x7f060017;
        public static final int ERR_025=0x7f060018;
        public static final int ERR_026=0x7f060019;
        public static final int ERR_027=0x7f06001a;
        public static final int ERR_028=0x7f06001b;
        public static final int ERR_029=0x7f06001c;
        public static final int ERR_030=0x7f06001d;
        public static final int ERR_031=0x7f06001e;
        public static final int ERR_032=0x7f06001f;
        public static final int ERR_033=0x7f060020;
        public static final int ERR_034=0x7f060021;
        public static final int EXPCATEGORY_EDIT_ISEXCLUDEFROMMILEAGECOST_LABEL=0x7f0600f8;
        public static final int EXPENSEEDIT_ACTIVITY_WARNING_LABEL=0x7f0600f9;
        public static final int GEN_AMOUNT_LABEL=0x7f06005b;
        public static final int GEN_BTNDONE_LABEL=0x7f06005a;
        public static final int GEN_CANCEL=0x7f060042;
        public static final int GEN_CAR_LABEL=0x7f060052;
        public static final int GEN_CHOOSEONE_DIALOGTITLE=0x7f060047;
        public static final int GEN_CHOOSEONE_MESSAGE=0x7f060048;
        public static final int GEN_CHOOSE_DIALOGTITLE=0x7f060049;
        public static final int GEN_CONVERTEDAMOUNT_LABEL=0x7f06005d;
        public static final int GEN_CONVRATE_LABEL=0x7f06005c;
        public static final int GEN_DELETE_CONFIRM=0x7f060050;
        public static final int GEN_DOCUMENTNO_LABEL=0x7f060056;
        public static final int GEN_DRIVER_LABEL=0x7f060053;
        public static final int GEN_EXPENSECATEGORY_LABEL=0x7f060054;
        public static final int GEN_EXPENSETYPE=0x7f060051;
        public static final int GEN_EXPENSETYPE_LABEL=0x7f060055;
        public static final int GEN_FILL_MANDATORY=0x7f060045;
        public static final int GEN_INDEX_LABEL=0x7f060057;
        public static final int GEN_ISACTIVE_LABEL=0x7f06004a;
        public static final int GEN_LBLDATETIME_CAPTION=0x7f06004d;
        public static final int GEN_NAME_LABEL=0x7f06004c;
        public static final int GEN_NO=0x7f060044;
        public static final int GEN_NUMBER_FORMAT_EXCEPTION=0x7f060046;
        public static final int GEN_OK=0x7f060041;
        public static final int GEN_PICK_DATE_BUTTON_CAPTION=0x7f06004e;
        public static final int GEN_PICK_TIME_BUTTON_CAPTION=0x7f06004f;
        public static final int GEN_PRICE_LABEL=0x7f060059;
        public static final int GEN_QUANTITY_LABEL=0x7f060058;
        public static final int GEN_USER_COMMENT_LABEL=0x7f06004b;
        public static final int GEN_YES=0x7f060043;
        public static final int GPSTRACK_ACTIVITY_CREATEMILEAGE_LABEL=0x7f06010e;
        public static final int GPSTRACK_ACTIVITY_FILEFORMAT_LABEL=0x7f06010d;
        public static final int GPSTRACK_ACTIVITY_GPSTRACKSTART_BTN_CAPTION=0x7f06010b;
        public static final int GPSTRACK_ACTIVITY_GPSTRACKSTOP_BTN_CAPTION=0x7f06010c;
        public static final int GPSTRACK_SERVICE_GPSTRACKSERVICEINPROGRESS_MESSAGE=0x7f06010f;
        public static final int INACTIVE_CAR_SELECTED_ERROR_MESSAGE=0x7f06009a;
        public static final int INACTIVE_DRIVER_SELECTED_ERROR_MESSAGE=0x7f060091;
        public static final int LM_MAIN_ACTIVITY_WELLCOME_MESSAGE2=0x7f060022;
        public static final int MAINSCREENPREF_ACTIVITY_LABEL=0x7f060101;
        public static final int MAIN_ACTIVITY_BACKUPEXISTS=0x7f06008c;
        public static final int MAIN_ACTIVITY_EXPENSELIST_BTN_CAPTION=0x7f06007c;
        /** 
    <string name="MAIN_ACTIVITY_GPSTRACKSTART_BTN_CAPTION">"Start GPS Track"</string>
    <string name="MAIN_ACTIVITY_GPSTRACKSTOP_BTN_CAPTION">"Stop GPS Track"</string>
    <string name="MAIN_ACTIVITY_GPSTRACKSERVICESTARTED_MESSAGE">"GPS tracking started"</string>
    <string name="MAIN_ACTIVITY_GPSSHOWMAP_BTN_CAPTION">"show map"</string>

         */
        public static final int MAIN_ACTIVITY_EXPENSE_HDR_CAPTION=0x7f060079;
        public static final int MAIN_ACTIVITY_EXPENSE_LISTHDR_CAPTION=0x7f06007a;
        public static final int MAIN_ACTIVITY_GPSTRACKLIST_BTN_CAPTION=0x7f060078;
        public static final int MAIN_ACTIVITY_GPSTRACK_HDR_CAPTION=0x7f060075;
        public static final int MAIN_ACTIVITY_GPSTRACK_LISTHDR_CAPTION=0x7f060076;
        public static final int MAIN_ACTIVITY_INSERT_EXPENSE_BTN_CAPTION=0x7f06007b;
        public static final int MAIN_ACTIVITY_INSERT_GPSTRACK_BTN_CAPTION=0x7f060077;
        public static final int MAIN_ACTIVITY_INSERT_MILEAGE_BTN_CAPTION=0x7f06006f;
        public static final int MAIN_ACTIVITY_INSERT_REFUEL_BTN_CAPTION=0x7f060073;
        public static final int MAIN_ACTIVITY_MILEAGELIST_BTN_CAPTION=0x7f060070;
        public static final int MAIN_ACTIVITY_MILEAGE_HDR_CAPTION=0x7f06006d;
        public static final int MAIN_ACTIVITY_MILEAGE_LISTHDR_CAPTION=0x7f06006e;
        public static final int MAIN_ACTIVITY_NOEXPENSETEXT=0x7f060087;
        public static final int MAIN_ACTIVITY_NOEXPENSE_ADITIONAL_TEXT=0x7f060088;
        public static final int MAIN_ACTIVITY_NOMILEAGETEXT=0x7f060085;
        public static final int MAIN_ACTIVITY_NOREFUELTEXT=0x7f060086;
        public static final int MAIN_ACTIVITY_NO_CURRENT_CAR=0x7f060089;
        public static final int MAIN_ACTIVITY_NO_CURRENT_DRIVER=0x7f06008a;
        public static final int MAIN_ACTIVITY_REFUELLIST_BTN_CAPTION=0x7f060074;
        public static final int MAIN_ACTIVITY_REFUEL_HDR_CAPTION=0x7f060071;
        public static final int MAIN_ACTIVITY_REFUEL_LISTHDR_CAPTION=0x7f060072;
        public static final int MAIN_ACTIVITY_STATISTICS_AVGCONS_LABEL=0x7f060080;
        public static final int MAIN_ACTIVITY_STATISTICS_AVGCONS_NODATA=0x7f060081;
        public static final int MAIN_ACTIVITY_STATISTICS_BTN_CAPTION=0x7f06007f;
        public static final int MAIN_ACTIVITY_STATISTICS_HDR_CAPTION=0x7f06007d;
        public static final int MAIN_ACTIVITY_STATISTICS_LISTHDR_CAPTION=0x7f06007e;
        public static final int MAIN_ACTIVITY_STATISTICS_MILEAGEEXP=0x7f060084;
        public static final int MAIN_ACTIVITY_STATISTICS_NOSTAT=0x7f060082;
        public static final int MAIN_ACTIVITY_STATISTICS_TOTALEXP=0x7f060083;
        public static final int MAIN_ACTIVITY_UPDATE_MESSAG=0x7f06008e;
        public static final int MAIN_ACTIVITY_WELCOMEBACK=0x7f06008b;
        public static final int MAIN_ACTIVITY_WELLCOME_MESSAGE_TITLE=0x7f06008d;
        public static final int MENU_ABOUT_CAPTION=0x7f060060;
        public static final int MENU_ADD_NEW_CAPTION=0x7f060063;
        public static final int MENU_DELETE_CAPTION=0x7f060062;
        public static final int MENU_EDIT_CAPTION=0x7f060064;
        public static final int MENU_EXPENSES_CAPTION=0x7f06006b;
        public static final int MENU_GPSTRACK_CAPTION=0x7f06006c;
        public static final int MENU_HELP_CAPTION=0x7f060061;
        public static final int MENU_HIDEINACTIVE_CAPTION=0x7f060066;
        public static final int MENU_MILEAGE_CAPTION=0x7f060069;
        public static final int MENU_PREFERENCES_CAPTION=0x7f06005e;
        public static final int MENU_REFUEL_CAPTION=0x7f06006a;
        public static final int MENU_REPORTS_CAPTION=0x7f06005f;
        public static final int MENU_REPORT_CAPTION=0x7f060068;
        public static final int MENU_SEARCH_CAPTION=0x7f060067;
        public static final int MENU_SHOWINACTIVE_CAPTION=0x7f060065;
        /** Stop index OR mileage
         */
        public static final int MILEAGE_EDIT_ACTIVITY_COMMENT=0x7f0600ab;
        public static final int MILEAGE_EDIT_ACTIVITY_HDRINSERTMODE_CAPTION=0x7f0600aa;
        public static final int MILEAGE_EDIT_ACTIVITY_INDEXHEADER=0x7f0600a6;
        public static final int MILEAGE_EDIT_ACTIVITY_INSERTOK_MESSAGE=0x7f0600ac;
        public static final int MILEAGE_EDIT_ACTIVITY_OPTION_INDEX=0x7f0600a8;
        public static final int MILEAGE_EDIT_ACTIVITY_OPTION_MILEAGE=0x7f0600a9;
        public static final int MILEAGE_EDIT_ACTIVITY_STARTINDEX=0x7f0600a7;
        public static final int MILEAGE_EDIT_ACTIVITY_UPDATEOK_MESSAGE=0x7f0600ad;
        public static final int MILEAGE_LISTREPORT_ACTIVITY_NOCOMMENT_TEXT=0x7f0600ae;
        public static final int NO_DRIVERS=0x7f060090;
        public static final int PREF_BKRESTORE_CATEGORY_TITLE=0x7f0600c4;
        public static final int PREF_BKRESTORE_SUMMARY=0x7f0600c6;
        public static final int PREF_BKRESTORE_TITLE=0x7f0600c5;
        public static final int PREF_CARSDRIVER_CATEGORY_TITLE=0x7f0600b7;
        public static final int PREF_CARS_SUMMARY=0x7f0600b9;
        public static final int PREF_CARS_TITLE=0x7f0600b8;
        public static final int PREF_CAT_CURRENCYLIST_SUMMARY=0x7f0600c3;
        public static final int PREF_CAT_CURRENCYLIST_TITLE=0x7f0600c2;
        public static final int PREF_CAT_CURRENCYRATELIST_TITLE=0x7f0600cc;
        public static final int PREF_CAT_CURRENCYRATELIS_SUMMARY=0x7f0600cd;
        public static final int PREF_CAT_EXPCATEGORY_SUMMARY=0x7f0600c8;
        public static final int PREF_CAT_EXPCATEGORY_TITLE=0x7f0600c7;
        public static final int PREF_CAT_EXPTYPE_SUMMARY=0x7f0600b6;
        public static final int PREF_CAT_EXPTYPE_TITLE=0x7f0600b5;
        public static final int PREF_CAT_MAINSCREENCATEGORY_SUMMARY=0x7f0600cb;
        public static final int PREF_CAT_MAINSCREENCATEGORY_TITLE=0x7f0600ca;
        public static final int PREF_DRIVERS_SUMMARY=0x7f0600bb;
        public static final int PREF_DRIVERS_TITLE=0x7f0600ba;
        public static final int PREF_EXPENSE_CATEGORY_TITLE=0x7f0600b4;
        public static final int PREF_GPSTRACK_CATEGORY_TITLE=0x7f0600ce;
        public static final int PREF_GPSTRACK_FILEFORMATCSV_TITLE=0x7f0600d5;
        public static final int PREF_GPSTRACK_FILEFORMATGPX_SUMMARY=0x7f0600d9;
        public static final int PREF_GPSTRACK_FILEFORMATGPX_TITLE=0x7f0600d8;
        public static final int PREF_GPSTRACK_FILEFORMATKML_SUMMARY=0x7f0600d7;
        public static final int PREF_GPSTRACK_FILEFORMATKML_TITLE=0x7f0600d6;
        public static final int PREF_GPSTRACK_FILEFORMAT_SUMMARY=0x7f0600d4;
        public static final int PREF_GPSTRACK_FILEFORMAT_TITLE=0x7f0600d3;
        public static final int PREF_GPSTRACK_MAXACCURACYSHUTDOWNLIMIT_SUMMARY=0x7f0600e5;
        public static final int PREF_GPSTRACK_MAXACCURACYSHUTDOWNLIMIT_TITLE=0x7f0600e4;
        public static final int PREF_GPSTRACK_MAXACCURACY_SUMMARY=0x7f0600e3;
        public static final int PREF_GPSTRACK_MAXACCURACY_TITLE=0x7f0600e2;
        public static final int PREF_GPSTRACK_MINDISTANCE_SUMMARY=0x7f0600dd;
        public static final int PREF_GPSTRACK_MINDISTANCE_TITLE=0x7f0600dc;
        public static final int PREF_GPSTRACK_MINTIME_SUMMARY=0x7f0600db;
        public static final int PREF_GPSTRACK_MINTIME_TITLE=0x7f0600da;
        public static final int PREF_GPSTRACK_SHOWONMAP_SUMMARY=0x7f0600d2;
        public static final int PREF_GPSTRACK_SHOWONMAP_TITLE=0x7f0600d1;
        public static final int PREF_GPSTRACK_SUMMARY=0x7f0600d0;
        public static final int PREF_GPSTRACK_TITLE=0x7f0600cf;
        public static final int PREF_MISC_CATEGORY_TITLE=0x7f0600c9;
        public static final int PREF_SENDCRASHREPORT_SUMMARY=0x7f0600e1;
        public static final int PREF_SENDCRASHREPORT_TITLE=0x7f0600e0;
        public static final int PREF_SENDUSAGESTATS_SUMMARY=0x7f0600df;
        public static final int PREF_SENDUSAGESTATS_TITLE=0x7f0600de;
        public static final int PREF_UOMCONVERSION_SUMMARY=0x7f0600c1;
        public static final int PREF_UOMCONVERSION_TITLE=0x7f0600c0;
        public static final int PREF_UOMLENGTH_SUMMARY=0x7f0600bd;
        public static final int PREF_UOMLENGTH_TITLE=0x7f0600bc;
        public static final int PREF_UOMS_CATEGORY_TITLE=0x7f0600b3;
        public static final int PREF_UOMVOLUME_SUMMARY=0x7f0600bf;
        public static final int PREF_UOMVOLUME_TITLE=0x7f0600be;
        public static final int RECORD_SELECTED_TOAST_MESSAGE=0x7f0600e6;
        public static final int REFUEL_BASEUOMQTY_LABEL=0x7f0600b0;
        public static final int REFUEL_ISFULLREFUEL_LABEL=0x7f0600af;
        public static final int REFUEL_NOUOMCONVERSION_MSG=0x7f0600b1;
        public static final int REPORTLIST_REPORT_CREATED=0x7f0600ee;
        public static final int REPORTOPTIONS_DIALOG_FORMAT_LABEL=0x7f0600ed;
        public static final int REPORTOPTIONS_DIALOG_SAVELOCAL_CAPTION=0x7f0600eb;
        public static final int REPORTOPTIONS_DIALOG_SENDEMAIL_CAPTION=0x7f0600ec;
        public static final int REPORTOPTIONS_DIALOG_TITLE=0x7f0600ea;
        public static final int REPORT_PROGRESS_DIALOG_TEXT=0x7f060105;
        public static final int REPORT_SERVICE_LABEL=0x7f060104;
        public static final int REPORT_SERVICE_STARTED=0x7f060102;
        public static final int REPORT_SERVICE_STOPPED=0x7f060103;
        public static final int SEARCH_DIALOG_TITLE=0x7f0600e7;
        public static final int SEARCH_FROM_DATE_LBL=0x7f0600e8;
        public static final int SEARCH_TO_DATE_LBL=0x7f0600e9;
        public static final int SERVICE_GPSTRACK_ACCURACYPROBLEM=0x7f060109;
        public static final int SERVICE_GPSTRACK_AUTOSHUTDOWN_MSG=0x7f06010a;
        public static final int SERVICE_GPSTRACK_GPSDISABLED=0x7f060108;
        public static final int SERVICE_GPSTRACK_LABEL=0x7f060106;
        public static final int SERVICE_GPSTRACK_SERVICESTOPPED_MESSAGE=0x7f060107;
        public static final int UOMCONVERSION_EDIT_ACTIVITY_CODE=0x7f0600a1;
        public static final int UOMCONVERSION_EDIT_ACTIVITY_RATE=0x7f0600a4;
        public static final int UOMCONVERSION_EDIT_ACTIVITY_UOMFROM=0x7f0600a2;
        public static final int UOMCONVERSION_EDIT_ACTIVITY_UOMTO=0x7f0600a3;
        public static final int UOM_CANNOT_DELETE_ERROR_MESSAGE=0x7f0600a0;
        public static final int UOM_EDIT_ACTIVITY_CODE=0x7f06009d;
        public static final int UOM_EDIT_ACTIVITY_TITLE_LENGTH=0x7f06009e;
        public static final int UOM_EDIT_ACTIVITY_TITLE_VOLUME=0x7f06009f;
    }
}
